name: 'Git Diff Sort'
description: 'Provides various Git diff outputs'
branding:
  color: 'orange'
  icon: 'filter'
inputs:
  meta_file_name:
    description: 'Name of the YAML file containing metadata'
    required: false
  keyword:
    description: 'Keyword to look for in the YAML file'
    required: false
  comparing_branch:
    description: 'Branch to compare with'
    required: false
  comparing_tag:
    description: 'Tag to compare with'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Check if Python 3 is installed
      id: check_python
      run: |
        if python3 --version; then
          echo "Python3 is installed"
          echo "python_installed=0" >> $GITHUB_ENV
        else
          echo "Python3 is not installed"
          echo "python_installed=1" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Set up Python
      if: env.python_installed == 1
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Git diff
      run: |
        pwd
        echo $GITHUB_WORKSPACE
        git diff --name-only "remotes/origin/${{ inputs.comparing_branch }}"
      shell: bash
    - name: Run Python script
      run: python3 ${{ github.action_path }}/src/main.py --meta_file_name=${{ inputs.meta_file_name }} --keyword=${{ inputs.keyword }} --comparing_branch=${{ inputs.comparing_branch }} --comparing_tag=${{ inputs.comparing_tag }}
      id: git-diff
      shell: bash

outputs:
  distinct_folders:
    value: ${{ steps.git-diff.outputs.distinct_folders }}
    description: 'Distinct folders from Git diff'
  folders_without_metadata:
    value: ${{ steps.git-diff.outputs.folders_without_metadata }}
    description: 'Folders without any metadata file'
  folders_sorted_alpha_inc:
    value: ${{ steps.git-diff.outputs.folders_sorted_alpha_inc }}
    description: 'Folders sorted alphabetically (incremental)'
  folders_sorted_alpha_dec:
    value: ${{ steps.git-diff.outputs.folders_sorted_alpha_dec }}
    description: 'Folders sorted alphabetically (decremental)'
  folders_sorted_meta_inc:
    value: ${{ steps.git-diff.outputs.folders_sorted_meta_inc }}
    description: 'Folders sorted based on metadata (incremental)'
  folders_sorted_meta_dec:
    value: ${{ steps.git-diff.outputs.folders_sorted_meta_dec }}
    description: 'Folders sorted based on metadata (decremental)'
  json:
    value: ${{ steps.git-diff.outputs.json }}
    description: 'All the different outputs in JSON format, you can access json.distinct_folders[]'
